name: Build and Deploy to Azure Container App

on:
  push:
    branches:
      - main

env:
  ACR_NAME: acrjovanlab001
  IMAGE_NAME: demo-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: az acr login --name $ACR_NAME

      - run: |
          docker build -f ./app/Dockerfile -t $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }} ./app
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}

      - run: |
          az extension add --name containerapp --upgrade

          echo "=== LIST RESOURCE GROUP ==="
          az group list -o table

          echo "=== LIST CONTAINER APPS ==="
          az containerapp list -o table

          echo "=== TRY UPDATE ==="
          az containerapp update \
            --name demo-app-container \
            --resource-group rg-containerapp-lab \
            --image $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}